#User Configuration
#vcu feature is needed for EV variants only
MACHINE_FEATURES:append = " vcu"

#OE_TERMINAL = "tmux"

RM_WORK_EXCLUDE += "axi-dma"
RM_WORK_EXCLUDE += "linux-xlnx device-tree"

REPRODUCIBLE_BUILD = "0"